apiVersion: apps/v1
kind: Deployment
metadata:
  name: bz-edge-service
  labels:
    app: bz-edge-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bz-edge-service
  template:
    metadata:
      labels:
        app: bz-edge-service
    spec:
      containers:
        - name: bz-edge-service
          image: bz-edge-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9999
          env:
            - name: BZ_AUTH_SERVICE_URL
              value: http://bz-auth-service:90
            - name: BZ_FRONT_SERVICE_URL
              value: http://bz-front-service:90
#            - name: BZ_PROD_SERVICE_URL
#              value: http://bz-prod-service:90
            - name: BZ_SELLER_SERVICE_URL
              value: http://bz-seller-service:90
            - name: BZ_CUSTOMER_SERVICE_URL
              value: http://bz-customer-service:90
            - name : BZ_ADMIN_SERVICE
              value: http://bz-admin-service:90
            - name: BZ_OOTD_SERVICE
              value: http://bz-ootd-service:90
            - name: BZ_AD_SERVICE
              value: http://bz-ad-service:90
#            - name: SPRING_CLOUD_CONFIG_URI
#              value: http://config-service:8888
#            - name: SPRING_REDIS_HOST
#              value: polar-redis